export const CODES = {
  USER: {
    INACTIVE: 'ERROR:USER-INACTIVE',
    USERNAME_TAKEN: 'ERROR:USER-USERNAME_TAKEN',
    EDIT_ONLY_YOURSELF: 'ERROR:USER-EDIT_ONLY_YOURSELF',
    NOT_LOGGED_IN: 'ERROR:USER-NOT_LOGGED_IN!'
  },
  AUTH: {
    WRONG_CREDENTIALS: 'ERROR:AUTH-WRONG_CREDENTIALS',
    RESTRICTED_IP: 'ERROR:AUTH-RESTRICTED_IP',
    OFF_HOURS: 'ERROR:AUTH-OFF_HOURS',
    WRONG_AUTH_TYPE: 'ERROR:AUTH-WRONG_AUTH_TYPE',
    INVALID_SPECIAL_CODE: 'ERROR:AUTH-INVALID_SPECIAL_CODE',
    NO_AUTH_HEADER: 'ERROR:AUTH-NO_AUTH_HEADER',
    NO_TOKEN: 'ERROR:AUTH-NO_TOKEN',
    NO_TOKEN_PAYLOAD: 'ERROR:AUTH-NO_TOKEN_PAYLOAD'
  },
  SESSION: {
    EMPTY: 'ERROR:TOKEN-EMPTY',
    WRONG_DEVICE: 'ERROR:TOKEN-WRONG_DEVICE',
    EXPIRED: 'ERROR:TOKEN-EXPIRED',
  },
  COMMON: {
    UNKNOWN: 'ERROR:SYSTEM-UNKNOWN!',
    HTTP: 'ERROR:SYSTEM-HTTP_EXCEPTION',
    EMPTY_EMAIL: 'ERROR:SYSTEM-EMAIL_REQUIRED',
    EMPTY_PARAM: 'ERROR:SYSTEM-EMPTY_PARAM'
  },
  CODE: {
    INVALID: 'ERROR:CODE-INVALID',
    UNKNOWN: 'ERROR:CODE-UNKNOWN',
    EXPIRED: 'ERROR:CODE-EXPIRED',
    WRONG_RELATED_TO: 'ERROR:CODE-NOT_YOURS_BITCH'
  },
  DATABASE: {
    DUPLICATE: 'ERROR:DATABASE-DUPLICATE'
  },
  VALIDATION: 'ERROR:VALIDATION',
  HTTP: {
    '400': 'ERROR:HTTP-BAD_REQUEST',
    '401': 'ERROR:HTTP-UNAUTHORIZED',
    '403': 'ERROR:HTTP-FORBIDDEN_RESOURCE',
    '404': 'ERROR:HTTP-NOT_FOUND',
  },
  LICENSE: {
    NOT_FOUND: 'ERROR:LICENSE-NOT_FOUND'
  },
  WORKSPACE: {
    NOT_FOUND: 'ERROR:WORKSPACE-NOT_FOUND',
    NO_ACCESS: 'ERROR:WORKSPACE-NO_ACCESS'
  },
  FEATURE: {
    NOT_AVAILABLE: 'ERROR:FEATURE-NOT_AVAILABLE'
  },
  PERMISSION: {
    NOT_FOUND: 'ERROR:PERMISSION-NOT_FOUND',
    NONE_AVAILABLE: 'ERROR:PERMISSIONS-NONE_AVAILABLE'
  }
}