export const CODES = {
  MONGO: {
    INVALID_BSON_ID: 'VALIDATION:INVALID_BSON_ID'
  },
  USER: {
    INACTIVE: 'ERROR:USER-INACTIVE',
    USERNAME_TAKEN: 'ERROR:USER-USERNAME_TAKEN',
    NOT_FOUND: 'ERROR:USER-NOT_FOUND',
    EDIT_ONLY_YOURSELF: 'ERROR:USER-EDIT_ONLY_YOURSELF',
    NOT_LOGGED_IN: 'ERROR:USER-NOT_LOGGED_IN!',
    ALREADY_VERIFIED: 'ERROR:USER-ALREADY-VERIFIED'
  },
  AUTH: {
    WRONG_CREDENTIALS: 'ERROR:AUTH-WRONG_CREDENTIALS',
    RESTRICTED_IP: 'ERROR:AUTH-RESTRICTED_IP',
    OFF_HOURS: 'ERROR:AUTH-OFF_HOURS',
    WRONG_AUTH_TYPE: 'ERROR:AUTH-WRONG_AUTH_TYPE',
    INVALID_SPECIAL_CODE: 'ERROR:AUTH-INVALID_SPECIAL_CODE',
    NO_AUTH_HEADER: 'ERROR:AUTH-NO_AUTH_HEADER',
    NO_TOKEN: 'ERROR:AUTH-NO_TOKEN',
    NO_TOKEN_PAYLOAD: 'ERROR:AUTH-NO_TOKEN_PAYLOAD'
  },
  SESSION: {
    EMPTY: 'ERROR:TOKEN-EMPTY',
    WRONG_DEVICE: 'ERROR:TOKEN-WRONG_DEVICE',
    EXPIRED: 'ERROR:TOKEN-EXPIRED',
  },
  COMMON: {
    UNKNOWN: 'ERROR:SYSTEM-UNKNOWN!',
    HTTP: 'ERROR:SYSTEM-HTTP_EXCEPTION',
    EMPTY_EMAIL: 'ERROR:SYSTEM-EMAIL_REQUIRED',
    EMPTY_PARAM: 'ERROR:SYSTEM-EMPTY_PARAM'
  },
  CODE: {
    INVALID: 'ERROR:CODE-INVALID',
    UNKNOWN: 'ERROR:CODE-UNKNOWN',
    EXPIRED: 'ERROR:CODE-EXPIRED',
    WRONG_RELATED_TO: 'ERROR:CODE-NOT_YOURS_BITCH'
  },
  DATABASE: {
    DUPLICATE: 'ERROR:DATABASE-DUPLICATE'
  },
  VALIDATION: 'ERROR:VALIDATION',
  HTTP: {
    '400': 'ERROR:HTTP-BAD_REQUEST',
    '401': 'ERROR:HTTP-UNAUTHORIZED',
    '403': 'ERROR:HTTP-FORBIDDEN_RESOURCE',
    '404': 'ERROR:HTTP-NOT_FOUND',
    BAD_INPUT: 'ERROR:HTTP-BAD_INPUT'
  },
  LICENSE: {
    NOT_FOUND: 'ERROR:LICENSE-NOT_FOUND'
  },
  WORKSPACE: {
    NOT_FOUND: 'ERROR:WORKSPACE-NOT_FOUND',
    NO_ACCESS: 'ERROR:WORKSPACE-NO_ACCESS'
  },
  WORKSPACE_INFO: {
    NOT_FOUND: 'ERROR:WORKSPACE_INFO-NOT_FOUND',
    DOMAIN_TAKEN: 'ERROR:WORKSPACE_INFO-DOMAIN_TAKEN'
  },
  FEATURE: {
    NOT_AVAILABLE: 'ERROR:FEATURE-NOT_AVAILABLE'
  },
  PERMISSION: {
    NOT_FOUND: 'ERROR:PERMISSION-NOT_FOUND',
    NONE_AVAILABLE: 'ERROR:PERMISSION-NONE_AVAILABLE',
    RELATED_DEFINITION_NOT_FOUND: 'VALIDATION:RELATED_PERMISSION_DEFINITION-NOT_FOUND',
    RELATED_GROUP_NOT_FOUND: 'VALIDATION:RELATED_PERMISSION_GROUP-NOT_FOUND'
  },
  PERMISSION_SET: {
    NOT_FOUND: 'ERROR:PERMISSION_SET-NOT_FOUND',
    ASSIGNEE_NOT_FOUND: 'VALIDATION:PERMISSION_SET-ASSIGNEE-NOT_FOUND'
  },
  PERMISSION_OPTIONS: {
    NOT_FOUND: 'ERROR:PERMISSION_OPTIONS-NOT_FOUND'
  },
  PERMISSION_ASSIGNMENT: {
    RELATED_PERMISSION_NOT_FOUND: 'VALIDATION:RELATED_PERMISSION-NOT_FOUND',
    RELATED_PERMISSION_SET_NOT_FOUND: 'VALIDATION:RELATED_PERMISSION_SET-NOT_FOUND',
    RELATED_PERMISSION_DOES_NOT_HAVE_OPTIONS: 'VALIDATION:RELATED_PERMISSION-NOT_OPTIONS_SPECIFIED',
    RELATED_PERMISSION_DOES_NOT_HAVE_SPECIFIED_OPTION: 'VALIDATION:RELATED_PERMISSION-DOES_NOT_HAVE_SPECIFIED_OPTION'
  },
  OBJECT_METADATA: {
    NOT_FOUND: 'ERROR:OBJECT_METADATA:NOT_FOUND',
    DUPLICATE_API_NAME: 'ERROR:OBJECT_METADATA:DUPLICATE_API_NAME',
    CANNOT_DELETE_STANDARD: 'ERROR:OBJECT_METADATA:CANNOT_DELETE_STANDARD',
    CANNOT_EDIT_STANDARD: 'ERROR:OBJECT_METADATA:CANNOT_EDIT_STANDARD',
    USED_AS_RELATION: 'ERROR:OBJECT_METADATA.USED_AS_RELATION'
  },
  FIELD_METADATA: {
    NOT_FOUND: 'ERROR:FIELD_METADATA:NOT_FOUND',
    DUPLICATE_API_NAME: 'ERROR:FIELD_METADATA:DUPLICATE_API_NAME',
    CANNOT_DELETE_STANDARD: 'ERROR:FIELD_METADATA:CANNOT_DELETE_STANDARD',
    CANNOT_EDIT_STANDARD: 'ERROR:FIELD_METADATA:CANNOT_EDIT_STANDARD',
    RELATED_OBJECT_DOES_NOT_EXIST: 'ERROR:FIELD_METADATA:RELATED_OBJECT_DOES_NOT_EXIST',
    RELATED_KEY_FIELD_DOES_NOT_EXIST: 'ERROR:FIELD_METADATA:RELATED_KEY_FIELD_DOES_NOT_EXIST',
  },

}